Module7 task2
htmlacademy-yii/1101403-task-force-1 pull request #19
Opened 2020-09-25 19:18 UTC by nejgauz

2020-09-29 19:34 UTC, caseycs commented on frontend/models/CreateTaskForm.php
> +    public $category = [
Категории у нас уже есть и хранятся в БД - думаю разумнее взять их оттуда, нежели хардкодить тут.

2020-09-29 19:59 UTC, caseycs requested changes
Два главных момента - брать категории из БД и валидировать цену.

2020-09-29 19:59 UTC, caseycs commented on frontend/models/CreateTaskForm.php
> +                ['title', 'category', 'attachments', 'budget', 'dt_end'], 'required', 'message' => 'Поле не может быть пустым'
Для budget нужна еще валидация на целое число больше нуля

2020-09-29 19:59 UTC, caseycs commented on frontend/controllers/TasksController.php
> +                        $filePath = __DIR__ . '\..\web\uploads\\' . uniqid() . '.' . $file->extension;
Я бы не стал доверять расширению, которое пришло из браузера пользователя, но в данном проекте - думаю это нормально.

2020-09-29 19:59 UTC, caseycs commented on frontend/controllers/TasksController.php
> +        if (Yii::$app->request->isPost) {
Ради читаемости кода и уменьшения глубины вложенности я бы вынес все что внутри условия в отдельную функцию или же поменял бы условия на обратное с тем, чтобы перенести 

```
 return $this->render('create', [
            'model' => $model,
            'errors' => $errors
        ]);
```

наверх - return early https://www.google.com/search?ei=M5FzX_LRKYyakwXDzqPwBw&q=programming+return+early&oq=programming+return+&gs_lcp=CgZwc3ktYWIQAxgAMgIIADICCAAyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeOgQIABBHOggIIRAWEB0QHlCjD1icF2D7IWgAcAJ4AIAB8QGIAdMGkgEFMC4yLjKYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=psy-ab

2020-09-29 19:59 UTC, caseycs commented on frontend/controllers/TasksController.php
> +                        if ($file->saveAs($filePath)) {
А если не получилось? Раз уж ты обрабатываешь ошибки сохранение - надо что-то делать и в случае неудачи. Хотя бы бросить исключение и показать фатальную ошибку, а в идеале - такую же ошибку как и прочие ошибки валидации. 

Также открытый вопрос - а если файл не сохранился, надо ли сохраняться новую задачу и модель с этим файлом в БД? Тут нет правильного ответа, скорее food for thought.

2020-09-30 17:31 UTC, nejgauz commented on frontend/models/CreateTaskForm.php
> +                ['title', 'category', 'attachments', 'budget', 'dt_end'], 'required', 'message' => 'Поле не может быть пустым'
Я еще сейчас увидела примечание "Не заполняйте для оценки исполнителем", из чего я сделала вывод, что требуется, чтобы поле могло быть пустым. Однако, если оно заполнено, то число должно быть целое и больше нуля. Так что в новых правках учту оба параметра.

2020-09-30 20:53 UTC, nejgauz commented on frontend/controllers/TasksController.php
> +                        if ($file->saveAs($filePath)) {
Предполагаю, что в приложении должна быть возможность редактировать задание. Тогда если файл не сохранился, то впоследствии его будет возможно попробовать загрузить снова. 
Моя ситуация осложняется тем, что мне требуется id задания для сохранения файла. А этот id задание получает автоматически только при сохранении в БД. Т.е. я могу узнать id задания только после того, как сохраню его в БД. 
Поскольку id задания для файла - это обязательное поле, то по логике я могу попробовать сохранить файл только после сохранения задания. 
То есть единственное, что я могу предпринять в такой ситуации, на мой взгляд, это как-то предупредить юзера, что файл не сохранился. 
Либо я что-то упускаю.

2020-10-01 10:12 UTC, caseycs commented on frontend/controllers/TasksController.php
> +                        if ($file->saveAs($filePath)) {
Верно. Тут нет однозначного ответа, но можно выбрать чем жертвовать. Поясню.

Если мы записали строчку в БД, а файл на самом деле не сохранили - это прямо плохо - БД, наш источник правды содержит некорректные данные. Можно удалять все, что записали в БД если файл не сохранили (или откатить транзакцию - если они используются) - но это тоже так себе, корявенько. Но и сохранять файл, пока мы в БД ничего не записали - тоже не очень хорошо, ведь и запись в БД может упасть с ошибкой.

Как правило выбирают лишний раз записать файл, чем иметь потенциально не-целостную БД, то есть: сперва сохраняют файлы (имена файлов случайные, никакого id в них нет), а потом уже (если все хорошо) - записывают данные в базу.

2020-10-01 18:11 UTC, merged